id: P004616
initial_creation_type: ocr
source_metadata:
  id: bdr:W5JW7
  title: སིདཏ-སངརབ༹
  author: ''
  volumes:
    4002f0da2a5c4864b21cb47f4afde8ef:
      image_group_id: I1KG15559
      title: ''
      volume_number: 1
      total_pages: 147
      base_file: v001.txt
