id: ID387C665
legacy_id: P004616
ocr_import_info:
  bdrc_scan_id: W5JW7
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T04:49:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:08:05.581685+00:00'
last_modified: 2022-09-04 11:08:16.997272
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W5JW7
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW5JW7
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: sidat-sangarava
  author: Herbert V. Günther
statistics:
  ocr_word_mean_confidence_index: 0.9076464406267702
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG15559:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15559
      total_pages: 147
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15559.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9076464406267702
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
