id: ID387C665
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T04:51:04+00:00'
last_modified: '2022-06-08T02:20:18.335929+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W5JW7
  title: སིདཏ-སངརབ༹
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F453:
      image_group_id: I1KG15559
      title: ''
      total_pages: 147
      order: 1
      base_file: F453.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
